### ISSUE TITLE
Class 'noam148\imageresize\FileNotFoundException' not found

### ISSUE THREAD

**Issue by maiconcarlos** [noam148/yii2-image-resize#1]
`<?php echo Yii::$app->imageresize->getUrl(Yii::getAlias('@web/images/imoveis/Chrysanthemum.jpg'), '480', '360', 'outbound', '70', $foto->imo_fot_nome); ?>`

The image exists in the folder, and the code below works perfectly.

`<img src="<?php echo Yii::getAlias('@web/images/imoveis/Chrysanthemum.jpg')?>">`

Any suggestion?

**Comment by noam148** [comment]
Hi @maiconcarlos, sorry for my late response and thanks for reporting! I wil take a look what's going wrong today or tomorrow. I let you know!

**Comment by noam148** [comment]
@maiconcarlos the "Class not found" error is fixed, now I used yii\base\Exception if the file not exists.

The reason why the component not found your image is because it needs the absolute webroot path. So if you replace @web by @webroot it needs to work. Don't forget to update the component (fix to the the right exception class).

The method Yii::getAlias() is not realy needed because it's already run in the component.

I hope this fixed your issue. If you had any questions, let me know!
